"""Writing datapacks to disk."""
from __future__ import annotations

import json
import os
import zipfile
from pathlib import Path

from .registry import CATEGORIES
from .templates import PACK_FORMAT, TEMPLATES


def write_json(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def id_to_path(root: Path, category: str, ident: str) -> Path:
    namespace, rel = ident.split(":", 1) if ":" in ident else ("minecraft", ident)
    return root / "data" / namespace / CATEGORIES[category] / (rel + ".json")


class PackWriter:
    def __init__(self, root, description: str = "", version: str = "26.2"):
        self.root = Path(root)
        self.description = description
        self.version = version
        self.written: list[Path] = []

    def mcmeta(self) -> None:
        fmt = PACK_FORMAT.get(self.version, 107)
        pack = {"pack_format": fmt, "description": self.description or self.root.name}
        if fmt > 81:
            # 26.x refuses a pack that declares a format above 81 without these:
            # "Pack declares support for version newer than 81, but is missing
            #  mandatory fields min_format and max_format"
            pack["min_format"] = [fmt, 0]
            pack["max_format"] = [fmt, 99]
        write_json(self.root / "pack.mcmeta", {"pack": pack})
        self.written.append(self.root / "pack.mcmeta")

    def add(self, category: str, ident: str, obj) -> Path:
        path = id_to_path(self.root, category, ident)
        write_json(path, obj)
        self.written.append(path)
        return path

    def add_all(self, files: dict[str, dict]) -> None:
        for category, entries in files.items():
            for ident, obj in entries.items():
                self.add(category, ident, obj)

    def relative(self) -> list[str]:
        return [str(p.relative_to(self.root)).replace(os.sep, "/") for p in self.written]


def scaffold(root, namespace: str, name: str, template: str = "basic",
             description: str = "", version: str = "26.2",
             replace_overworld: bool = False) -> PackWriter:
    """Create a complete, loadable pack to edit."""
    if template not in TEMPLATES:
        raise ValueError(f"unknown template '{template}' (have: {', '.join(sorted(TEMPLATES))})")
    files = TEMPLATES[template](namespace, name)
    writer = PackWriter(root, description or f"{name} - generated by worldsmith", version)
    writer.mcmeta()
    writer.add_all(files)
    if replace_overworld:
        dimension = files["dimension"][f"{namespace}:{name}"]
        writer.add("dimension", "minecraft:overworld", dimension)
    return writer


def export_zip(root, out_path) -> Path:
    root = Path(root)
    out_path = Path(out_path)
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(root.rglob("*")):
            if path.is_file():
                zf.write(path, path.relative_to(root).as_posix())
    return out_path
